// Boss Mode Helpers — report generation, smart auto-assign algorithm, and analytics calculation.

import { store } from '../state';
import { fmtCost, fmtTokens, tokensOf, type WorkerInfo } from '../../shared/protocol';
import { toast } from './dom';

/**
 * Finds the most idle worker on the floor for Smart Auto-Assign.
 * 1. Returns an idle worker (sorted by least recent input / earliest creation).
 * 2. If no idle workers, returns a completed/done worker (sorted by longest waiting time).
 * 3. Fallback: returns any non-working and non-needs_input worker.
 */
export function findMostIdleWorker(workers: Iterable<WorkerInfo>): WorkerInfo | null {
  const all = [...workers];
  if (!all.length) return null;

  // 1. Idle workers first (sorted by least recent input or earliest creation)
  const idles = all
    .filter((w) => w.status === 'idle')
    .sort((a, b) => (a.lastInput?.at ?? a.createdAt) - (b.lastInput?.at ?? b.createdAt));
  if (idles.length > 0) return idles[0];

  // 2. Done workers next
  const dones = all
    .filter((w) => w.status === 'done')
    .sort((a, b) => (a.waitingSince ?? a.createdAt) - (b.waitingSince ?? b.createdAt));
  if (dones.length > 0) return dones[0];

  // 3. Fallback: non-working, non-needs_input workers
  const fallback = all.filter((w) => w.status !== 'working' && w.status !== 'needs_input');
  if (fallback.length > 0) return fallback[0];

  return null;
}

/**
 * Exports a detailed Markdown summary of the current floor's active workers, open PRs, tasks, and spend.
 */
export function exportFloorReport() {
  const workers = [...store.workers.values()];
  const floorName = store.project?.name || 'Agent Office';
  const totalCount = workers.length;
  const workingCount = workers.filter((w) => w.status === 'working').length;
  const needsInputCount = workers.filter((w) => w.status === 'needs_input').length;
  const doneCount = workers.filter((w) => w.status === 'done').length;
  const idleCount = totalCount - workingCount - needsInputCount - doneCount;

  let totalTokens = 0;
  let totalCost = 0;
  for (const w of workers) {
    if (w.usage) {
      totalTokens += tokensOf(w.usage);
      totalCost += w.usage.cost || 0;
    }
  }

  const timestamp = new Date();
  const lines: string[] = [
    `# 👔 Boss Control Center — Floor Executive Report`,
    ``,
    `**Generated At:** ${timestamp.toLocaleString()}`,
    `**Floor / Project:** ${floorName}`,
    ``,
    `---`,
    ``,
    `## 📊 Live Analytics Summary`,
    `- **Total Workers Hired:** ${totalCount}`,
    `- **Active (Working):** ${workingCount}`,
    `- **Needing Input:** ${needsInputCount}`,
    `- **Completed (Done):** ${doneCount}`,
    `- **Idle / Standby:** ${idleCount}`,
    `- **Total Tokens Used:** ${fmtTokens(totalTokens)} (${totalTokens.toLocaleString()} tokens)`,
    `- **Total Dollar Spend:** ${fmtCost(totalCost)}`,
    ``,
    `---`,
    ``,
    `## 👷 Worker Breakdown`,
  ];

  if (!workers.length) {
    lines.push(`*No workers currently hired on this floor.*`);
  } else {
    lines.push(
      `| Name | ID | Status | Provider / Model | Task / Current Activity | Tokens | Spend | PR |`,
      `| --- | --- | --- | --- | --- | --- | --- | --- |`,
    );

    for (const w of workers) {
      const statusText = w.status === 'needs_input' ? 'NEEDS INPUT' : w.status.toUpperCase();
      const providerModel = [w.provider, w.model].filter(Boolean).join('/') || 'default';
      const rawActivity = w.task?.name || w.activity || w.title || w.prompt || '—';
      const activity = rawActivity.replace(/\|/g, '\\|');
      const tokens = w.usage ? fmtTokens(tokensOf(w.usage)) : '0';
      const spend = w.usage?.cost != null ? fmtCost(w.usage.cost) : '$0.00';
      const prText = w.pr ? `[#${w.pr.number}](${w.pr.url})` : '—';

      lines.push(`| **${w.name}** | \`${w.id}\` | ${statusText} | ${providerModel} | ${activity} | ${tokens} | ${spend} | ${prText} |`);
    }
  }

  const openPrs = workers.filter((w) => w.pr);
  if (openPrs.length > 0) {
    lines.push(``, `---`, ``, `## 🔀 Active Pull Requests`);
    for (const w of openPrs) {
      if (w.pr) {
        lines.push(`- **${w.name}**: [#${w.pr.number}](${w.pr.url}) — Branch: \`${w.worktree?.branch || 'main'}\``);
      }
    }
  }

  lines.push(``, `---`, `*End of Report — Generated by Agent Office Boss Control System*`);

  const mdContent = lines.join('\n');
  const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `floor-report-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  toast('Floor report downloaded successfully!');
}
