/** Post-merge instructions, editable as part of the PR board agent's brief. */
export const PR_MAINTENANCE = `After each authorized merge, finish the local handoff and clean up that PR's branches. This is part of the merge request; it does not authorize other merges or new tasks. Obey repository rules and author restrictions.

Verify on GitHub that the PR is MERGED and record its repository, base, head branch, head SHA and merge commit. Fetch the matching remote with pruning; pruning remote-tracking refs does not delete local branches. A closed PR or a missing remote branch is not proof of integration.

Update the intended local main (or the PR's actual base branch), not just origin/main. Confirm the repository and checkout path; inspect git worktree list --porcelain, branch/upstream, status including untracked files, and active workers, meetings and builds. A separately configured user checkout is a separate clone: fetch and check it separately. Do not search for or change unrelated clones. In a clean, idle checkout already on the base, use a fast-forward-only merge of its freshly fetched remote base. Immediately recheck that it is still clean and idle before updating, then verify HEAD and status. Do not switch the shared checkout's branch. If the base is not checked out anywhere, only advance its ref after an ancestor check, with git update-ref's expected old SHA. Local changes, divergence, an active writer/build or uncertain ownership mean leave that checkout intact and report why. Never stash, reset, force-update or discard someone's work to catch it up.

Delete only the verified merged PR's head branch, never a default/protected/base branch. Check for other open PRs, active worker or meeting ownership, and all worktrees first. Keep checked-out branches and worker worktrees, even when idle, for the office's existing lifecycle controls. Keep anything with uncommitted work, unpushed or additional commits, or uncertain integration. A squash merge is not an ancestry merge: verify the exact PR head was merged and the candidate branch has no later commits. For a same-repository remote branch, re-read its tip and delete only with an explicit force-with-lease tied to that verified head SHA; a changed tip means skip. Never delete a fork branch without separate authorization. For an unused local branch, verify its tip and complete inclusion (ancestry or exact merged PR head evidence for a squash), recheck ownership and tip immediately before deletion, and preserve it if anything changed. No blanket branch deletion, git clean, forced worktree removal, or sending workers home.

Report three separate outcomes: PR merged, local base updated (path and SHA) or deferred (reason), and branches removed or kept (reason). A deferred local update or cleanup must not block the next independent authorized PR. Retry it at the next regular handoff after rechecking; do not start a background polling loop.`;
